# -*- coding: utf-8 -*-
"""DataCleaningInPandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oY83xx-2btX3gVL5Sbc7IBM621S0SbD2

# Data Cleaning in Pandas:
"""

import pandas as pd
df=pd.read_excel('/Customer Call List.xlsx')
df

df=df.drop_duplicates()
df

df=df.drop(columns='Not_Useful_Column')
df

df["Last_Name"]=df["Last_Name"].str.lstrip("...")
df["Last_Name"]=df["Last_Name"].str.lstrip("/")
df["Last_Name"]=df["Last_Name"].str.rstrip("_")
#df["Last_Name"]=df["Last_Name"].str.strip("_/.123")
df

df['Phone_Number']=df["Phone_Number"].str.replace('|','')
df

df['Phone_Number']=df["Phone_Number"].str.replace('Na','')
df['Phone_Number']=df['Phone_Number'].astype(str)
df['Phone_Number']=df['Phone_Number'].str.replace('nan','')
df['Phone_Number']=df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df

"""lets split address"""

df['Address'] = df['Address'].astype(str).str.strip('[]').str.strip()
df[['Street', 'City_State_Zip']] = df["Address"].str.split(',', n=1, expand=True)
df['Street'] = df['Street'].str.strip()
df['City_State_Zip'] = df['City_State_Zip'].str.strip()
df