# -*- coding: utf-8 -*-
"""PandasEx1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPwmO0BNAZ0vTDxGfnf7fKSeGE5cOm2X
"""

import pandas as pd
import numpy as np

"""Lets read hotel find and cleanse"""

readHotelcsv=pd.read_csv('/content/hotel-booking-data.csv', delimiter='\t')
readHotelcsv.head()
#readHotelcsv.count()
len(readHotelcsv)



readHotelcsv.describe()

readHotelcsv['Company'].value_counts()

readHotelcsv.dropna()

readHotelcsv['newcolumn']='dummydata'
readHotelcsv