# -*- coding: utf-8 -*-
"""VisualizeDataInPandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGPYc-dLQD2VwEhO4AlcgVZmOCHbO7Uv

# **Visualizing Data in Pandas**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as mplot

df=pd.read_csv("/Ice Cream Ratings.csv")
df.set_index("Date")
df

df.plot(title='Ice Cream Ratings', xlabel='Daily ratings', ylabel='Scores')
print(mplot.style.available)
mplot.style.use('Solarize_Light2')

#df.plot(kind='bar')
#df.plot(kind='bar', stacked=True)
df['Flavor Rating'].plot(kind='bar', stacked=True)

df.plot.barh(stacked = True)

df.plot(kind='scatter', x='Texture Rating', y='Overall Rating', s=100, c='Red')

df.plot.hist(bins= 10)

df.boxplot()

df.plot.area(figsize=(10,5))

df.plot.pie(figsize=(5,6), y='Flavor Rating', subplots=True)